### PR TITLE
adding jed1.x

### PR DESCRIPTION
**Pull request by emosesSfdc**
I don't actually know that much about Jed format, but this was a quick-and-dirty way to make it work.  I imagine you'll want to clean it up.  There's one thing I'm not sure about, which I commented on below.

### CODE REVIEW

**Comment by datakurre** [comment]
@Sinewyk Thank you for your jed1.x patch. Any news on finishing this pull to make it official? :)

**Comment by Sinewyk** [comment]
Hmm, this is coming from far away.

But if you correctly transform ouput from Jed 1.1.x to what you want, then it should be good enough for you ^^, then it's good enough for me.

PS: I'm seriously sorry about all that mess ... I should have emphasized more to SlexAxton that bumping to 2.x would be better to exactly avoid these problems. I guess we both underestimated how his Jed repo was relied upon, and I messed things up just because of a [null, ...] that I thought just had no sense being there ... sorry :disappointed:

**Comment by JSteunou** [comment]
So what's the status on this guys? Is it possible to use Jed 1.1.0 with po2json?

**Comment by mikeedwards** [comment]
Hey, apologies for the delay. I've been dragging my feet to see if anything changes upstream in Jed. I'll take a another look at the state of Jed and the PR again this afternoon. Most likely, I'll merge it in and up the minor version. Thanks for your patience.

**Comment by JSteunou** [comment]
No problem I'm patient :) Thank you for your work.

**Pull request merged**
