### PR TITLE
wrap msgstr into an Array to be able translate correctly languages without plural form (one form provided)

### PR DESCRIPTION
**Pull request by rafalt-iRonin**
Hey,

I prepared a patch for Japanese. Does it make sense to merge in?
I also thought about fixing it directly in `gettext-parser` but it would require additional amount of work.

Cheers!

### CODE REVIEW

**Comment by mikeedwards** [comment]
Thanks!

**Comment by rafaltrojanowski** [comment]
Oh! Thanks for the quick action. And further changes.

**Comment by Timothee** [comment]
Hm, this actually broke things for me. As far as I can tell, `gettext-parser` already returns an array when there's only one plural.

I tried the following code: (in a place where I have both `gettext-parser` and `po2json` (for the fixtures) installed naturally)

```js
var gettextParser = require("gettext-parser");

var input = require('fs').readFileSync('node_modules/po2json/test/fixtures/ja.po');
var po = gettextParser.po.parse(input);
console.log('Japanese');
console.log('=====');
console.log(po.translations['']['result']);
console.log('');

var input = require('fs').readFileSync('node_modules/po2json/test/fixtures/pl.po');
var po = gettextParser.po.parse(input);
console.log('Polish');
console.log('=====');
console.log(po.translations['']['one product']);
```

It simply runs `gettext-parser` on the existing fixtures for Japanese and Polish and prints a particular object that has a plural from the existing fixtures.

The output of `node test.js` is:
```js
Japanese
=====
{ msgid: 'result', msgid_plural: 'results', msgstr: [ '検索結果' ] }

Polish
=====
{ msgid: 'one product',
  comments: { reference: 'test.js:4' },
  msgid_plural: '%d products',
  msgstr: [ 'jeden produkt', '%d produkty', '%d produktów' ] }
```

As you can see, in Japanese, `msgstr` is an array like in Polish. The strange thing is that I've tried that with both `gettext-parser@1.1.0` (the one pinned in `po2json`) and `gettext-parser@1.2.0` (the one just released after [a fix for the inverse issue in the compiler](https://github.com/smhg/gettext-parser/pull/19/)) and I get the same results.

Am I missing something?

**Comment by jknight12882** [comment]
This broke things for me as well. See issue #57

**Pull request merged**
